=== floortom/xml-essential-training-3817215/Start/Ch9/productlist.xsd
<?xml version="1.0" encoding="utf-8" ?> 
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">
    <xsd:element name="productlist">
        <xsd:complexType>
            <xsd:sequence>
                <xsd:element name="product" maxOccurs="unbounded">
                    <xsd:complexType>
                        <xsd:all>
                            <xsd:element name="name">
                                <xsd:complexType mixed="true">
                                    <xsd:attribute name="instock" type="xsd:boolean"></xsd:attribute>
                                </xsd:complexType>
                            </xsd:element>
                            <xsd:element name="price">
                                <xsd:simpleType>
                                    <xsd:restriction base="xsd:string">
                                        <xsd:pattern value="\d+\.\d{1,2}"></xsd:pattern>
                                    </xsd:restriction>
                                </xsd:simpleType>
                            </xsd:element>
                        </xsd:all>
                    </xsd:complexType>
                </xsd:element>
            </xsd:sequence>
        </xsd:complexType>
    </xsd:element>
</xsd:schema>

=== floortom/xml-essential-training-3817215/Start/Ch9/productlist.xml
<?xml version="1.0" encoding="UTF-8"?>
<productlist xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="productlist.xsd">
    <product>
        <name instock="true">Product 1</name>
        <price>200.00</price>
    </product>
    <product>
        <name instock="true">Product 2</name>
        <price>300.00</price>
    </product>
    <product>
        <name instock="false">Product 3</name>
        <price>400.00</price>
    </product>
</productlist>
