=== floortom/xml-essential-training-3817215/Start/Ch8/products.dtd
<!ELEMENT productlist (product+)>

<!ELEMENT product (name, price)>

<!ELEMENT name (#PCDATA)>
<!ELEMENT price (#PCDATA)>

<!ATTLIST name instock (true|false) #REQUIRED>
<!ATTLIST price currency (USD|CAD|EUR|PLN) #REQUIRED>

=== floortom/xml-essential-training-3817215/Start/Ch8/products.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE productlist SYSTEM "products.dtd">
<productlist>
    <product>
        <name instock="true">Product 1</name>
        <price currency="USD">200.00</price>
    </product>
    <product>
        <name instock="true">Product 2</name>
        <price currency="EUR">300.00</price>
    </product>
    <product>
        <name instock="false">Product 3</name>
        <price currency="CAD">400.00</price>
    </product>
</productlist>
